# Dependencies
markdown:         kramdown
highlighter:      rouge

kramdown:
  input:          GFM

# Permalinks
permalink:        pretty

# Setup
title:            Data Carpentry for Biologists
description:      'UMBC BTEC 330'
url:              http://www.datacarpentry.org/semester-biology
baseurl:          /semester-biology
email:            rahm0054@umbc.edu
feedbackurl:      docs.google.com/forms/d/1y35uJukuZ9MPKQWWqw0Y8R4VOiaOtFJezDY_t_kJfTs/
author:
  name:           'Nandita Rahman'
  url:            https://www.linkedin.com/in/nanditarahman/

github:
  repo:           https://github.com/rahm0054/semester-biology
  #               Be sure the 'Issues' feature is activated in 'Settings'

plugins:
  - jekyll-sitemap
